#!/usr/bin/env python3
from sys import argv
with open(argv[1], "r") as f:
    for x in f:
        y = int(x)
        m = { 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97}
        for i in m:
            if (y % i) is 0:
                p = int(y / i)
                q = i
                print("{}={}*{}".format(y, p, q))
                break
        if i is 97:
            n = int(y ** 0.5)
            p = n + 1
            q = n
            while (p * q != y):
                if (p * q < y):
                    p += 1
                else:
                    q -= 1
            print("{}={}*{}".format(y, p, q))
